-- Supabase schema for Stream Live Admins
-- Run in Supabase SQL Editor.

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('superadmin','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.admin_profiles enable row level security;
alter table public.admin_requests enable row level security;

-- admin_profiles: user can read own row
drop policy if exists "read own profile" on public.admin_profiles;
create policy "read own profile"
on public.admin_profiles for select
to authenticated
using (user_id = auth.uid());

-- Only superadmins can manage profiles (do via SQL or Supabase dashboard service role)
drop policy if exists "no direct write profiles" on public.admin_profiles;
create policy "no direct write profiles"
on public.admin_profiles for all
to authenticated
using (false)
with check (false);

-- admin_requests: anyone can create request
drop policy if exists "insert requests" on public.admin_requests;
create policy "insert requests"
on public.admin_requests for insert
to anon, authenticated
with check (true);

-- requests readable only by superadmins via dashboard/service role (no client read)
drop policy if exists "no client read requests" on public.admin_requests;
create policy "no client read requests"
on public.admin_requests for select
to anon, authenticated
using (false);
